language: ruby
rvm:
  - "2.2.2"
services:
  - postgresql
before_script:
  - export RAILS_ENV=test
  - bundle exec rake db:drop db:create db:migrate

script:
  - echo RAILS_ENV
  - RAILS_ENV=test bundle exec rspec
